# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25385014f9c18eb8f77f83a2214066ee4bb8982468003c7aa50026142ef5b78bfd6a4ad8b0eab222fd3eff9635bd17ca5c5d49c2de59cdb84332f62fd8f0b780

test:
  secret_key_base: 55e278b9a3d002de8a5b293db66471e38ccde35867d5ee0072be01807666c00d549b8014a096a3ec605e9bdd6943e331f1c644d27a4b0cbe397e836d8378138b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
